/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.GUI;
import Classes.Produtos;
import javax.swing.JOptionPane;

/**
 *
 * @author Erivan
 */
public class AdiAltProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdiAltProduto
     */
    public AdiAltProduto() {
        initComponents();

        setTitle("Adicionar Produto");
        tfCodigo.setText(gerarCodigo());
    }

    public AdiAltProduto(int codigo, String descricao, int unidades, float preco) {
        initComponents();

        setTitle("Alterar Produto");

        tfCodigo.setEditable(false);
        tfCodigo.setEnabled(false);

        tfCodigo.setText(Integer.toString(codigo));
        tfDescricao.setText(descricao);
        tfUnidades.setText(Integer.toString(unidades));
        tfPreco.setText(Float.toString(preco));
    }

    public static String gerarCodigo() {
        int maiorValor = 0;
        for (int i = 0; i < Produtos.getCodigo().size(); i++) {
            if (i == 0) {
                maiorValor = Produtos.getCodigo().get(i);
            } else {
                if (maiorValor < Produtos.getCodigo().get(i)) {
                    maiorValor = Produtos.getCodigo().get(i);
                }
            }
        }
        return Integer.toString(maiorValor + 1);
    }

    public static void limpar() {
        tfCodigo.setText(gerarCodigo());
        tfDescricao.setText("");
        tfUnidades.setText("");
        tfPreco.setText("");
        tfCodigo.requestFocus();
    }

    public javax.swing.JTextField getTfCodigo() {
        return tfCodigo;
    }

    public javax.swing.JTextField getTfDescricao() {
        return tfDescricao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnInformacoesBasicas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfDescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfUnidades = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfPreco = new javax.swing.JTextField();
        btConcluir = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pnInformacoesBasicas.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações Básicas"));

        jLabel1.setText("Código:");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        tfCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCodigoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCodigoFocusLost(evt);
            }
        });

        jLabel2.setText("Descrição:");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        tfDescricao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfDescricaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDescricaoFocusLost(evt);
            }
        });

        jLabel3.setText("Unidades:");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        tfUnidades.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfUnidades.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUnidadesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUnidadesFocusLost(evt);
            }
        });

        jLabel4.setText("Preço:");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        tfPreco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPrecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPrecoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnInformacoesBasicasLayout = new javax.swing.GroupLayout(pnInformacoesBasicas);
        pnInformacoesBasicas.setLayout(pnInformacoesBasicasLayout);
        pnInformacoesBasicasLayout.setHorizontalGroup(
            pnInformacoesBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInformacoesBasicasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnInformacoesBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnInformacoesBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnInformacoesBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnInformacoesBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnInformacoesBasicasLayout.createSequentialGroup()
                        .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addComponent(tfDescricao))
                .addContainerGap())
        );

        pnInformacoesBasicasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfPreco, tfUnidades});

        pnInformacoesBasicasLayout.setVerticalGroup(
            pnInformacoesBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInformacoesBasicasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnInformacoesBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnInformacoesBasicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btConcluir.setText("Concluir");
        btConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConcluirActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnInformacoesBasicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConcluir)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btCancelar, btConcluir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnInformacoesBasicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConcluir)
                    .addComponent(btCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCodigoFocusGained
        GUI.ganhaFoco(tfCodigo);
    }//GEN-LAST:event_tfCodigoFocusGained

    private void tfCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCodigoFocusLost
        GUI.perdeFoco(tfCodigo);
    }//GEN-LAST:event_tfCodigoFocusLost

    private void tfDescricaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDescricaoFocusGained
        GUI.ganhaFoco(tfDescricao);
    }//GEN-LAST:event_tfDescricaoFocusGained

    private void tfDescricaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDescricaoFocusLost
        GUI.perdeFoco(tfDescricao);
    }//GEN-LAST:event_tfDescricaoFocusLost

    private void tfUnidadesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUnidadesFocusGained
        GUI.ganhaFoco(tfUnidades);
    }//GEN-LAST:event_tfUnidadesFocusGained

    private void tfUnidadesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUnidadesFocusLost
        GUI.perdeFoco(tfUnidades);
    }//GEN-LAST:event_tfUnidadesFocusLost

    private void tfPrecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPrecoFocusGained
        GUI.ganhaFoco(tfPreco);
    }//GEN-LAST:event_tfPrecoFocusGained

    private void tfPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPrecoFocusLost
        GUI.perdeFoco(tfPreco);
    }//GEN-LAST:event_tfPrecoFocusLost

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        GUI.fechar(this);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        GUI.fechar(this);
    }//GEN-LAST:event_formInternalFrameClosing

    private void btConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConcluirActionPerformed
        try {
            if (tfCodigo.getText().trim().isEmpty() || tfDescricao.getText().trim().isEmpty() || tfUnidades.getText().trim().isEmpty() || tfPreco.getText().trim().isEmpty()) {
                JOptionPane.showInternalMessageDialog(rootPane, "Por favor preencha todos os campos.");
            } else {
                int codigo = Integer.parseInt(tfCodigo.getText());
                String descricao = tfDescricao.getText();
                int unidades = Integer.parseInt(tfUnidades.getText());
                float preco = Float.parseFloat(tfPreco.getText().replaceAll(",", "."));

                if (getTitle().contains("Adicionar")) {
                    if (Produtos.getCodigo().indexOf(codigo) != -1) {
                        JOptionPane.showInternalMessageDialog(rootPane, "Já existe um produto cadastro com esse código.\nPor favor, escolha outro código.");
                    } else {
                        Produtos.adicionarProduto(codigo, descricao, unidades, preco);

                        int resultado = JOptionPane.showInternalConfirmDialog(rootPane, "Operação realizada com sucesso.\nDeseja adicionar outro produto?");

                        if (resultado == JOptionPane.YES_OPTION) {
                            limpar();
                        } else {
                            dispose();
                        }
                    }
                } else {
                    Produtos.alterarProduto(codigo, descricao, unidades, preco);
                    JOptionPane.showInternalMessageDialog(rootPane, "Operação realizada com sucesso.");
                    dispose();
                    ConsultarProduto.pesquisar();
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showInternalMessageDialog(rootPane, "Falha ao realizar a operação:\n\n" + ex, "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btConcluirActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        tfCodigo.requestFocus();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        tfDescricao.requestFocus();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        tfUnidades.requestFocus();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        tfPreco.requestFocus();
    }//GEN-LAST:event_jLabel4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btConcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pnInformacoesBasicas;
    private static javax.swing.JTextField tfCodigo;
    private static javax.swing.JTextField tfDescricao;
    private static javax.swing.JTextField tfPreco;
    private static javax.swing.JTextField tfUnidades;
    // End of variables declaration//GEN-END:variables
}
