/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.GUI;
import Classes.Produtos;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erivan
 */
public class ConsultarProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarProduto
     *
     * @param titulo
     */
    public ConsultarProduto(String titulo) {
        initComponents();

        setTitle(titulo + " Produto");

        switch (titulo) {
            case "Alterar":
                btDeletarProduto.setVisible(false);
                break;
            case "Deletar":
                btAlterarProduto.setVisible(false);
                break;
        }
    }

    public static void pesquisar() {
        DefaultTableModel modeloTabela = (DefaultTableModel) tbTabelaProdutos.getModel();
        Object[] linha = new Object[4];

        modeloTabela.setRowCount(0);
        if (!tfProcurar.getText().trim().isEmpty()) {
            for (int i = 0; i < Produtos.getCodigo().size(); i++) {
                linha[0] = Produtos.getCodigo().get(i);
                linha[1] = Produtos.getDescricao().get(i);
                linha[2] = Produtos.getUnidades().get(i);
                linha[3] = Produtos.getPreco().get(i);
                if (rbCodigo.isSelected() && linha[0].toString().equals(tfProcurar.getText().trim())) {
                    modeloTabela.addRow(linha);
                } else if (rbDescricao.isSelected() && linha[1].toString().contains(tfProcurar.getText().trim())) {
                    modeloTabela.addRow(linha);
                }
            }
        }

        tbTabelaProdutos.setModel(modeloTabela);
    }

    public static void deletar() {
        if (tbTabelaProdutos.getSelectedRowCount() == 1) {
            if (JOptionPane.showInternalConfirmDialog(JanelaPrincipal.getDtDesktop(), "Deseja mesmo realizar essa operação?") == JOptionPane.YES_OPTION) {
                int linha = Produtos.getCodigo().indexOf(tbTabelaProdutos.getValueAt(tbTabelaProdutos.getSelectedRow(), 0));
                Produtos.deletarProduto(linha);
                pesquisar();
            }
        } else {
            JOptionPane.showInternalMessageDialog(JanelaPrincipal.getDtDesktop(), "Você precisa selecionar um produto.");
        }
    }

    public static void alterar() {
        if (tbTabelaProdutos.getSelectedRowCount() == 1) {
            int linhaSelecionada = tbTabelaProdutos.getSelectedRow();

            int codigo = (int) tbTabelaProdutos.getValueAt(linhaSelecionada, 0);
            String descricao = (String) tbTabelaProdutos.getValueAt(linhaSelecionada, 1);
            int unidades = (int) tbTabelaProdutos.getValueAt(linhaSelecionada, 2);
            float preco = (float) tbTabelaProdutos.getValueAt(linhaSelecionada, 3);

            AdiAltProduto obj = new AdiAltProduto(codigo, descricao, unidades, preco);
            GUI.criar(obj);
            obj.getTfDescricao().requestFocus();
        } else {
            JOptionPane.showInternalMessageDialog(JanelaPrincipal.getDtDesktop(), "Você precisa selecionar um produto.");
        }
    }

    public javax.swing.JTextField getTfProcurar() {
        return tfProcurar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pmnMenuTabela = new javax.swing.JPopupMenu();
        mniAlterarProduto = new javax.swing.JMenuItem();
        mniDeletarProduto = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTabelaProdutos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfProcurar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbCodigo = new javax.swing.JRadioButton();
        rbDescricao = new javax.swing.JRadioButton();
        btAlterarProduto = new javax.swing.JButton();
        btDeletarProduto = new javax.swing.JButton();

        mniAlterarProduto.setText("Alterar");
        mniAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAlterarProdutoActionPerformed(evt);
            }
        });
        pmnMenuTabela.add(mniAlterarProduto);

        mniDeletarProduto.setText("Deletar");
        mniDeletarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDeletarProdutoActionPerformed(evt);
            }
        });
        pmnMenuTabela.add(mniDeletarProduto);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tbTabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Unidades", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTabelaProdutos);
        if (tbTabelaProdutos.getColumnModel().getColumnCount() > 0) {
            tbTabelaProdutos.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Procurar por:");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        tfProcurar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfProcurarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfProcurarFocusLost(evt);
            }
        });
        tfProcurar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfProcurarKeyReleased(evt);
            }
        });

        jLabel2.setText("Filtro:");

        buttonGroup1.add(rbCodigo);
        rbCodigo.setText("Código");

        buttonGroup1.add(rbDescricao);
        rbDescricao.setSelected(true);
        rbDescricao.setText("Descrição");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDescricao)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfProcurar))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbCodigo)
                    .addComponent(rbDescricao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btAlterarProduto.setText("Alterar");
        btAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarProdutoActionPerformed(evt);
            }
        });

        btDeletarProduto.setText("Deletar");
        btDeletarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAlterarProduto)
                            .addComponent(btDeletarProduto, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAlterarProduto, btDeletarProduto});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAlterarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btDeletarProduto))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfProcurarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfProcurarFocusGained
        GUI.ganhaFoco(tfProcurar);
    }//GEN-LAST:event_tfProcurarFocusGained

    private void tfProcurarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfProcurarFocusLost
        GUI.perdeFoco(tfProcurar);
    }//GEN-LAST:event_tfProcurarFocusLost

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        tfProcurar.requestFocus();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarProdutoActionPerformed
        alterar();
    }//GEN-LAST:event_btAlterarProdutoActionPerformed

    private void btDeletarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletarProdutoActionPerformed
        deletar();
    }//GEN-LAST:event_btDeletarProdutoActionPerformed

    private void tfProcurarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfProcurarKeyReleased
        pesquisar();
    }//GEN-LAST:event_tfProcurarKeyReleased

    private void tbTabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTabelaProdutosMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON1 && evt.getClickCount() == 2) {
            alterar();
        } else if (evt.getButton() == MouseEvent.BUTTON3) {
            pmnMenuTabela.show(tbTabelaProdutos, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tbTabelaProdutosMouseClicked

    private void mniDeletarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDeletarProdutoActionPerformed
        deletar();
    }//GEN-LAST:event_mniDeletarProdutoActionPerformed

    private void mniAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAlterarProdutoActionPerformed
        alterar();
    }//GEN-LAST:event_mniAlterarProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarProduto;
    private javax.swing.JButton btDeletarProduto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mniAlterarProduto;
    private javax.swing.JMenuItem mniDeletarProduto;
    private javax.swing.JPopupMenu pmnMenuTabela;
    private static javax.swing.JRadioButton rbCodigo;
    private static javax.swing.JRadioButton rbDescricao;
    private static javax.swing.JTable tbTabelaProdutos;
    private static javax.swing.JTextField tfProcurar;
    // End of variables declaration//GEN-END:variables
}
