/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Arquivos;
import Classes.GUI;
import Classes.Produtos;
import java.beans.PropertyVetoException;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Erivan
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtDesktop = new javax.swing.JDesktopPane();
        mbBarraMenu = new javax.swing.JMenuBar();
        mnProduto = new javax.swing.JMenu();
        mniAdicionarProduto = new javax.swing.JMenuItem();
        mniAlterarProduto = new javax.swing.JMenuItem();
        mniConsultarProduto = new javax.swing.JMenuItem();
        mniDeletarProduto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniVenderProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Aula 8");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mnProduto.setText("Produto");

        mniAdicionarProduto.setText("Adicionar");
        mniAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAdicionarProdutoActionPerformed(evt);
            }
        });
        mnProduto.add(mniAdicionarProduto);

        mniAlterarProduto.setText("Alterar");
        mniAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAlterarProdutoActionPerformed(evt);
            }
        });
        mnProduto.add(mniAlterarProduto);

        mniConsultarProduto.setText("Consultar");
        mniConsultarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniConsultarProdutoActionPerformed(evt);
            }
        });
        mnProduto.add(mniConsultarProduto);

        mniDeletarProduto.setText("Deletar");
        mniDeletarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDeletarProdutoActionPerformed(evt);
            }
        });
        mnProduto.add(mniDeletarProduto);
        mnProduto.add(jSeparator1);

        mniVenderProduto.setText("Vender");
        mniVenderProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVenderProdutoActionPerformed(evt);
            }
        });
        mnProduto.add(mniVenderProduto);

        mbBarraMenu.add(mnProduto);

        setJMenuBar(mbBarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtDesktop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAdicionarProdutoActionPerformed
        AdiAltProduto obj = new AdiAltProduto();
        GUI.criar(obj);
        obj.getTfCodigo().requestFocus();
    }//GEN-LAST:event_mniAdicionarProdutoActionPerformed

    private void mniConsultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniConsultarProdutoActionPerformed
        ConsultarProduto obj = new ConsultarProduto("Consultar");
        GUI.criar(obj);
        obj.getTfProcurar().requestFocus();
    }//GEN-LAST:event_mniConsultarProdutoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        String dados = "";

        JInternalFrame[] jif = getDtDesktop().getAllFrames();
        if (jif.length == 0) {
            dispose();
        } else {
            for (int i = 0; i < jif.length; i++) {
                if (jif[i].getTitle().contains("Vender")) {
                    if (VenderProduto.fechar()) {
                        dispose();
                    }
                } else {
                    dispose();
                }
            }
        }

        for (int i = 0; i < Produtos.getCodigo().size(); i++) {
            dados = dados + Produtos.getCodigo().get(i) + ";";
            dados = dados + Produtos.getDescricao().get(i) + ";";
            dados = dados + Produtos.getUnidades().get(i) + ";";
            dados = dados + Produtos.getPreco().get(i) + "\n";
        }

        Arquivos.gravarProdutos(dados);
    }//GEN-LAST:event_formWindowClosing

    private void mniAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAlterarProdutoActionPerformed
        ConsultarProduto obj = new ConsultarProduto("Alterar");
        GUI.criar(obj);
        obj.getTfProcurar().requestFocus();
    }//GEN-LAST:event_mniAlterarProdutoActionPerformed

    private void mniDeletarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDeletarProdutoActionPerformed
        ConsultarProduto obj = new ConsultarProduto("Deletar");
        GUI.criar(obj);
        obj.getTfProcurar().requestFocus();
    }//GEN-LAST:event_mniDeletarProdutoActionPerformed

    private void mniVenderProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVenderProdutoActionPerformed
        VenderProduto obj = new VenderProduto();
        GUI.criar(obj);
        try {
            obj.setMaximum(true);
        } catch (PropertyVetoException ex) {
        }
        obj.getTfCodigo().requestFocus();
    }//GEN-LAST:event_mniVenderProdutoActionPerformed

    public static JDesktopPane getDtDesktop() {
        return dtDesktop;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        JFrame janela = new JanelaPrincipal();
        janela.setVisible(true);

        Arquivos.lerProdutos();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JDesktopPane dtDesktop;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar mbBarraMenu;
    private javax.swing.JMenu mnProduto;
    private javax.swing.JMenuItem mniAdicionarProduto;
    private javax.swing.JMenuItem mniAlterarProduto;
    private javax.swing.JMenuItem mniConsultarProduto;
    private javax.swing.JMenuItem mniDeletarProduto;
    private javax.swing.JMenuItem mniVenderProduto;
    // End of variables declaration//GEN-END:variables
}
